# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause


manifest:
  version: 0.13
  defaults:
    remote: ncs
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      revision: v3.3-branch
      import: true
      remote: ncs
  self:
    path: zego
